# Generated by Django 4.2.5 on 2023-11-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input the name of club', max_length=50, verbose_name='name of the club')),
                ('date_birth_club', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('name_division', models.CharField(help_text='Input the name', max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('clubs', models.ManyToManyField(to='Footballer.club')),
            ],
        ),
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(help_text='Input the name of position', max_length=50, primary_key=True, serialize=False, verbose_name='name position')),
                ('name_coach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('number_games', models.IntegerField()),
                ('id_user', models.ForeignKey(blank=True, help_text='Выберите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('division', models.ForeignKey(default='RPL', help_text='Input division', on_delete=django.db.models.deletion.CASCADE, to='Footballer.division', verbose_name='Division')),
                ('footballer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Footballer.footballer')),
            ],
        ),
        migrations.AddField(
            model_name='footballer',
            name='Position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Footballer.position'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='club',
            field=models.ForeignKey(help_text='Choose club', on_delete=django.db.models.deletion.CASCADE, to='Footballer.club', verbose_name='id CLUB'),
        ),
        migrations.AddField(
            model_name='footballer',
            name='id_user',
            field=models.ForeignKey(blank=True, help_text='Выберите id пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя'),
        ),
        migrations.AddField(
            model_name='division',
            name='referee',
            field=models.ForeignKey(help_text='Choose the referee', on_delete=django.db.models.deletion.CASCADE, to='Footballer.referee', verbose_name='Referee'),
        ),
    ]
